name: Build and Release PVE Upgrade Scripts

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Archive
        run: |
          mkdir dist
          tar -czvf dist/pve_helper_scripts.tar.gz pve-upgrade-orchestrator.sh pve-upgrade-dashboard.py pve8to9-upgrade.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          draft: false
          prerelease: false
          files: dist/pve_helper_scripts.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
