name: Build and Release PVE Upgrade Scripts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Prepare Files
        run: |
          mkdir -p dist
          cp -r pve8to9-upgrade dist/
          cp install.sh dist/

      - name: Create Tarball and Zip
        run: |
          cd dist
          tar -czvf pve_helper_scripts.tar.gz pve8to9-upgrade install.sh
          zip -r pve_helper_scripts.zip pve8to9-upgrade install.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          draft: false
          prerelease: false
          files: |
            dist/pve_helper_scripts.tar.gz
            dist/pve_helper_scripts.zip
            dist/install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
